### ISSUE TITLE
make: *** [Makefile:33: src/daemon.o] Error 127

### ISSUE THREAD

**Issue by ardakirci** [networkException/mbpfan#5]
I'm running Fedora 36 in MacBook Pro 16.1 and when I type "make" in terminal I get this error:

./configurePath.sh
 -------------------------------------
  Found fan at '/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:104/APP0001:00'

  For me the output was something like '/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:102/APP0001:00'.

  If your path looks completely different and the tests fail,
  try just using the normal (unpatched) version (git reset --hard origin/master).
  If that doesn't work either feel free to open an issue on github

  Patched mbpfan.c

  See further install instructions here:
  https://wiki.t2linux.org/guides/fan/
  It's advised to also run the tests to check if the patch was successful
 -------------------------------------
mkdir -p bin
Compiling src/daemon...
cc -c  -g  -Wall -Wextra -Wno-unused-function -std=c99 -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=500 src/daemon.c -osrc/daemon.o
make: cc: No such file or directory
make: *** [Makefile:33: src/daemon.o] Error 127

**Comment by networkException** [comment]
Do you have gcc installed?

**Comment by ardakirci** [comment]
Yep, that was the case. Sorry
